server:
<<<<<<< HEAD
  port: 8009
=======
  port: 8005
>>>>>>> branch 'master' of https://gitlab.navinfo.com/audi_group/audi_data_collect.git
  servlet:
    context-path: /audiDataCollect


spring:
  datasource :
      driver-class-name : org.postgresql.Driver
      url : jdbc:postgresql://36.111.83.14:5442/audi_data
      username : postgres
      password : superman

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  jpa:
      show-sql: true

logging:
  path: F:/audiDataCollect_loggings/
  file:
    max-history: 180